-- Legacy reference file.
-- The source of truth for the database schema is the SQL migration history in `supabase/migrations/`.
--
-- Apply schema changes with the Supabase CLI:
--   supabase login
--   supabase link --project-ref <project-ref>
--   supabase db push
